### ISSUE TITLE
Token Verification

### ISSUE THREAD

**Issue by musalawal04** [minswap/verified-tokens#10]
policy id: 37a2b93b4aa2b286b92b7099faff0bb87e0c629a5079c0584da2d577
Project: Osmium DAO
Categories: DAO
Website: https://osmiumdao.io
Twitter: https://twitter.com/OsmiumDAO_
Discord: https://discord.gg/HCt8cp3VgA

**Comment by rhodiumcoin1** [comment]
{
  "$policyId": {
    "project": string,
    "categories": string[],
    "socialLinks"?: {
      "website"?: string,
      "twitter"?: string,
      "discord"?: string,
      "telegram"?: string,
      "coinMarketCap"?: string,
      "coinGecko"?: string
    }
  }
}

**Comment by theuranus** [comment]
Verified policyId via: https://osmiumdao.io/get-os/
I'll add your token later

**Comment by theuranus** [comment]
Added in:  https://github.com/minswap/verified-tokens/pull/23
