### ISSUE TITLE
Rats DAO $RAT token verification

### ISSUE THREAD

**Issue by Agustinblockchain** [minswap/verified-tokens#104]
"discord": "https://discord.gg/qVmqWetXT3"
    }
  }
  "d5dec6074942b36b50975294fd801f7f28c907476b1ecc1b57c916ed": {
    "project": "Rats DAO",
    "categories": ["NFTs", "DAOs"],
    "socialLinks": {
      "website": "https://ratsdao.io/",
      "twitter": "https://twitter.com/ratsdao",
    }
  }
}

**Comment by theuranus** [comment]
Added in https://github.com/minswap/verified-tokens/pull/108
