### ISSUE TITLE
$MrHankey

### ISSUE THREAD

**Issue by BBAJake** [minswap/verified-tokens#1046]
Policy ID is on twitter page (Yes) 

{
"$policyID": 7c4389a89ae25d18c77c2347ee8df20b4a6278d34e6c550296eb710e
"project": string,
"categories": string[], "Meme"
"socialLinks"?: 
"website"?: string,https://mrhankey.io/ 
"twitter"?: http://twitter.com/MrHankeyPooCoin
"discord"?: https://discord.gg/jSnhGJZ3Ar
"telegram"?: string,
"coinMarketCap"?: string,
"coinGecko"?: string

**Comment by shadowkora** [comment]
Does not meet minimum pool TVL requirement

**Comment by BBAJake** [comment]
We closed the pool to move to v2 and are waiting for it to be verified. 

It was verified prior, on v1, why minswap removed the verification, I do not know. 

 






On Thursday, July 18, 2024 at 10:15:09 PM EDT, Patrik ***@***.***> wrote: 







Does not meet minimum pool TVL requirement
