### ISSUE TITLE
Verify VYRA Token

### ISSUE THREAD

**Issue by vyraio** [minswap/verified-tokens#106]
hi there, hope you fine!
i try to PR but i can't click on it ..
here is our file.
policy id on our website: https://vyra.io/connect/#1671500209294-8fe845fe-a4c6

Thank's for your work and have a great day!

{
    "493136618a39dcefb89ff573061f715ee32e88092d0299c54e3a3773":  {
      "project": "VYRA",
      "categories": ["Other"],
      "socialLinks"?: {
        "website"?: "https://vyra.io",
        "twitter"?: "https://twitter.com/vyraio"
        
      }
    }
  }

**Comment by theuranus** [comment]
Added in https://github.com/minswap/verified-tokens/pull/108
