### ISSUE TITLE
pull request for virus meme

### ISSUE THREAD

**Issue by virusinftoken** [minswap/verified-tokens#114]
Made a pull request a week ago but can't see it!
Please see to it or just add it to tokens.

"0fd9819a9d7fb414880883f43a42d33458f12bc5f9841cec6457dc15": {
    "project": "virusinftoken",
    "categories": ["Meme"],
    "socialLinks": {
      "website": "https://virusx.io",
      "twitter": "https://twitter.com/VirusXToken?t=GKGQqib-Dh-OJLbi19Aafw&s=09",
      "discord": "https://discord.gg/GbsYeYkM",
      "telegram": "https://t.me/+rt81kuRJO5hjZTU0"
    }
  }

**Comment by theuranus** [comment]
Added in https://github.com/minswap/verified-tokens/pull/119
