### ISSUE TITLE
CTV

### ISSUE THREAD

**Issue by jdivo10** [minswap/verified-tokens#116]
"9f452e23804df3040b352b478039357b506ad3b50d2ce0d7cbd5f806": {
    "project": "Cardano Token Vault",
    "categories": ["DAO", "DeFi"],
    "socialLinks": {
      "website": "https://adatokenvault.com/",
      "discord": "https://discord.gg/ctv",
      "twitter": "https://twitter.com/ADATOKENVAULT"
    }
  }

**Comment by theuranus** [comment]
Added in https://github.com/minswap/verified-tokens/pull/119
