### ISSUE TITLE
INVADA token verification

### ISSUE THREAD

**Issue by NileG0762** [minswap/verified-tokens#122]
Hello,

I need help with the registration of our INVADA token. I don't know how to make a pull request. Here is some information:
INVADA token policy: c448753e6dac6d4d3508e47f636122c715e3c8575955ae77307b305f
    project: ''INVADAZ'',
    categories:  "NFT",
    socialLinks:
      website: ''https://adainvadaz.com/''
      twitter: ''https://twitter.com/ADAINVADAZ''

Any additional information that you guys would need?

**Comment by theuranus** [comment]
Added in https://github.com/minswap/verified-tokens/pull/131
