### ISSUE TITLE
Crypto College token Verification (we have an LP on minswap already)

### ISSUE THREAD

**Issue by CryptoCollege1** [minswap/verified-tokens#146]
{
  "$policyId": {905da53004cfee0b8549285949aebedf82b5c6bb9a412cbd9658c6de
    "project": Crypto College,
    "categories":  "GameFi" |  "NFT" |  "DAO" | 
    "socialLinks"?: {
      "website"?: www.CryptoCollege.vip,
      "twitter"?: @crypto__college,
      "discord"?: https://discord.com/invite/KMme8JbBmR,
      "telegram"?: NA,
      "coinMarketCap"?: https://coinmarketcap.com/dexscan/cardano/aa2c53df861be243f0ed0188e8bf028cce82eeea81b5fa99ccd0d18138a52ab6/
      "coinGecko"?: NA
    }
  }
}

**Comment by tvtduy59** [comment]
The token was verified
