### ISSUE TITLE
$kekw Token Verification

### ISSUE THREAD

**Issue by kekwster** [minswap/verified-tokens#151]
Policy Id: 3ee8e0824a7a81bdc5bcacd004c25d3264dd8ac3eb4ab877b5d7d0ce
Project: $kekw
Categories: Meme
Social Links:
  Website: https://kekw.vip/
  Twitter: https://twitter.com/kekwcardano
  Discord: https://discord.gg/yGZmXcSRMY

**Comment by kekwster** [comment]
tysm for your attention.  I appreciate you and your teams hard work!

**Comment by shadowkora** [comment]
Added $kekw in PR #168
