### ISSUE TITLE
$PNG Verification

### ISSUE THREAD

**Issue by PNGcoinADA** [minswap/verified-tokens#159]
{
  "$policyId": {35e71ab6f55124a8f796df28382b24da36c6daf243cf622983408b52
    "project": string,
    "categories": string[], // some of the following:  "Meme" | "NFT" 
    "socialLinks"?: {
      "twitter"?: string, https://twitter.com/PNGcoinADA
      "telegram"?: string, https://t.co/9aiRFfOT9g
    }
  }
}

**Comment by shadowkora** [comment]
@PNGcoinADA  Please add your policyID to your twitter

**Comment by tvtduy59** [comment]
The Twitter account doesn't exist anymore
