### ISSUE TITLE
BLC token verification

### ISSUE THREAD

**Issue by Akinrov** [minswap/verified-tokens#17]
},
   "$policyId" :585cfcbdd0786e961187999e5d5d36b38d1ebc1c4112a0a95a8bd477": {
    "project": "BLC",
    "categories": ["Defi"],
    "socialLinks": {
      "website": "https://ibilecoin.com/",
      "discord": "https://discord.com/invite/NfZZN4AXrC",
      "twitter": "https://twitter.com/IBILECOIN1"
    }

**Comment by theuranus** [comment]
Verified 👍 Thank you

**Comment by Akinrov** [comment]
Thanks
