### ISSUE TITLE
$DSEEDS VERIFICATION dseedscoinada

### ISSUE THREAD

**Issue by mxmruss0413** [minswap/verified-tokens#185]
{
"$policyId": {17ac25e534f6c8d9a6a834601ae0a254f6f8ada8d5a6005d034a4fa
"project": string,
"categories": string[], // some of the following: "Meme" | "NFT"
"socialLinks"?: {
"twitter"?: string, https://twitter.com/dseedscoinada

**Comment by tvtduy59** [comment]
You must create a pool on our DEX first and the token logo is required now (you can update the logo on cardano-token-registry)

**Comment by shadowkora** [comment]
@mxmruss0413 ?
