### ISSUE TITLE
$redsnek verification

### ISSUE THREAD

**Issue by cardanodegen** [minswap/verified-tokens#187]
Policy :  ab4c7e9c04af09deeed47ab3bb42ad769c565642ef1d47204f7a16e4
Twitter: https://twitter.com/redsnekcoinada

Please let me know if I'm doing this right? Thank you Minswap Team!

**Comment by cardanodegen** [comment]
{
"$policyId": {ab4c7e9c04af09deeed47ab3bb42ad769c565642ef1d47204f7a16e4
"project": string,
"categories": string[], // some of the following: "Meme" | "NFT"
"socialLinks"?: {
"twitter"?: string, https://twitter.com/redsnekcoinada
}
}
}

**Comment by tvtduy59** [comment]
Logo is a must now for the verification. Please update your token logo on cardano-token-registry

**Comment by cardanodegen** [comment]
This is too difficult for my expertise. Please sir, I submitted this before we had to have a logo verified. Thank you.
