### ISSUE TITLE
$ARF Token Verification

### ISSUE THREAD

**Issue by arfsappyada** [minswap/verified-tokens#193]
{
  "$policyId": "d1407478fb3151f60fc533cd42d806dd7115cecfa25a018baf53c4dc" {
    "project": "ARF Sappy ADA",
    "categories": string["Meme"], 
    "socialLinks"?: {
      "twitter"?: "https://twitter.com/arfsappyada",
    }
  }
}

**Comment by tvtduy59** [comment]
This token is verified by https://github.com/minswap/verified-tokens/pull/200
