### ISSUE TITLE
verify token

### ISSUE THREAD

**Issue by McWojak** [minswap/verified-tokens#197]
{
  "$policyId": {"820182018282051a057d3ac98200581c39a1df51147b6de6689a4727846962fb6540c3a3c7859a1a79b9420f"
    "project": MCWOJAK,
    "categories": string[], // "Meme" 
    "socialLinks"?: {
      "website"?: string,
      "twitter"?: https://twitter.com/mcwojaketh,
      "discord"?: string,
      "telegram"?: string,
      "coinMarketCap"?: string,
      "coinGecko"?: string
    }
  }
}

**Comment by tvtduy59** [comment]
the policyId is not valid

**Comment by shadowkora** [comment]
@McWojak
