### ISSUE TITLE
Register metadata token: Ape Token

### ISSUE THREAD

**Issue by priceactionbars** [minswap/verified-tokens#224]
Hey I've contacted the support(ticket 2459) on discord regarding the Ape Token to register it. 

I've no any technical background to do this so he told the developers here will do for you if you provide the info you have/know.

I send you all info that I "know" regarding our Ape Token

Subject: This I don't know where to find
but my nami receiving adresse is:addr1q8nhm4mufz452rkjhtdlkhlsqkph66re803sq0e3mmvmhek49da079e03wg9ll5zjj89cyeuv5nhrxd0fkav3trzwz8qp6vqlr

Name: Ape Token

Description: Ape token is the first Ape Token on Cardano. 

Policy: This is I also don't know so you need to figure out for us 

Ticker: APE

url: https://iota-apes.com/

Logo:![1 (1).png](https://github.com/minswap/verified-tokens/assets/82802122/64434f10-51ed-46e5-8d75-2db444e99c10)

Decimals: 100 000 000 ( Hundred milion total supply)

(We have also a NFT collection named IOTA Robot Club Apes that has policy ID which will be launched next week, if this info is important you can use the info)

After this is done, I need probably  to verify the token they told me which is also important, but i need to put probably put Ada in the Ape Token pool probably first?

**Comment by priceactionbars** [comment]
will do next week, was busy, thank you for your patient.

**Comment by shadowkora** [comment]
@priceactionbars Bump, is there any update? (if there is no reply in 24h I will close this issue)

**Comment by priceactionbars** [comment]
I will create the token next friday or saturday. We were busy for other things.


I'll send you a message next friday or saturday.


See you

cheers

**Comment by priceactionbars** [comment]
Hey, i minted the token on cardano native token and i filled also the json file on 👇🏼 https://registry.cardano-native-token.com/create/eeestu9f5s00000 

Here is the json file i downloaded after i filled it in👇🏼
    https://docs.google.com/document/d/1ARPKdmOentQemMRL2AswI4D-sUGpxfJJ6Js_UNJEl_o/edit?usp=drivesdk

Can you also check if the metadata is correct and register it for me and verify it so i am able to see it on minswap and taptools.

Do you know why i don't see it on taptools recently added tokens and i don't see the logo in my etrnl wallet or minswap? but i am zble to see the logo on pools cardano adresse


One more question, i was not able to put twitter  account on the metadata only 1url? Will it be possible to add my twitter so it will be visible on taptools?

**Comment by shadowkora** [comment]
@priceactionbars It would be super helpful if you could fill these and most importantly the policyID (also the access to the google file is locked)
{
  "<your_policy_id>: {
    "project": <project_name>,
    "categories": <your_category>
    "socialLinks": {
      "website": <website_link>,
      "twitter": <website_link>,
      "discord": <website_link>,
      "telegram?: <website_link>
    }
  }
}

**Comment by shadowkora** [comment]
I see that you have yet to make a pool on Minswap @priceactionbars 
I can't add the token into the verified list until a pool is created.

**Comment by priceactionbars** [comment]
> I see that you have yet to make a pool on Minswap @priceactionbars 
> I can't add the token into the verified list until a pool is created.

First can you exactly tell me in your own words if i can make a pool and sell my all 100milion. I want to sell per 1 Ape for 0,01 Ada. My total balance of ADA i want to put is 50 ADA to start for all 100 milion. Or do i need more Ada into pool if i want to sell all 100 milion ape tokens. Which one is correct? Because i got confused and couldn't succeed when i want to to make the pool

**Comment by priceactionbars** [comment]
@shadowkora can you answer on my question
