### ISSUE TITLE
Verify token $MEH

### ISSUE THREAD

**Issue by MEHFER** [minswap/verified-tokens#228]
},
  "358e87af871fa88479b5e07f1744e2f866831f43a779e696ef945ee7": {
    "project": "MEH",
    "categories": ["Meme"],
    "socialLinks": {
      "discord": "https://discord.gg/yTbwKqyE",
      "twitter": "https://twitter.com/Mehcoinada",
       }

**Comment by MEHFER** [comment]
I hope I'm doing everything right. 
Please help me, thanks!

**Comment by shadowkora** [comment]
Added in #273
