### ISSUE TITLE
Verification request for $GRASS

### ISSUE THREAD

**Issue by dicaprigoat** [minswap/verified-tokens#244]
{
    "policyId": "32cc9c6c3456bc048d14a4a8e4ee3592e9664e8daac921a8ef52d92a",
    "project": "GOAT Tribe",
    "categories": "NFT" | "Utility"  | "DAO", 
    "name": "GRASS",
    "symbol": "GRASS",
    "website": "https://goattribe.io/",
     "twitter": "https://twitter.com/adaGOATS",
     "discord": "https://discord.gg/goattribe",
    "description": "GRASS Token powers the GOAT Tribe ecosystem",
    "totalSupply": 27,182,818,
    "amounts": [1],
    "decimalPlaces" : 6
}

**Comment by dicaprigoat** [comment]
It is done, place on the website now!

**Comment by shadowkora** [comment]
Can you please add the token logo to [cardano-token-registry](https://github.com/cardano-foundation/cardano-token-registry)?
Tag me here when you're done and I will verify your token in the next verification round

**Comment by shadowkora** [comment]
@dicaprigoat Bump (if there is no reply in 24h I will close this issue)

**Comment by dicaprigoat** [comment]
"policyId": "32cc9c6c3456bc048d14a4a8e4ee3592e9664e8daac921a8ef52d92a",
"project": "GOAT Tribe",
"categories": "NFT" | "Gaming" | "DAO",
"name": "GRASS",
"symbol": "GRASS",
"website": "https://goattribe.io/",
"twitter": "https://twitter.com/adaGOATS",
"discord": "https://discord.gg/T32WyzmA",
"description": "GRASS Token powers the GOAT Tribe ecosystem",
"totalSupply": 27,182,818,
"amounts": [1],
"decimalPlaces" : 6
