### ISSUE TITLE
ZALGO Coin

### ISSUE THREAD

**Issue by ZalgoBoss** [minswap/verified-tokens#252]
{
  "4a50a3c79cd9365b8eb10e257865f93f0e05d79004b409956fdcb3a8": {
    "project": "ZALGO",
    "categories": ["Meme"],
    "socialLinks": {
      "twitter": "https://twitter.com/ZALGOCoin",
      "discord": "https://discord.com/invite/ZALGOCoin"
    }
  }
}

**Comment by shadowkora** [comment]
Added in #273
