### ISSUE TITLE
Verify Financial Advice token

### ISSUE THREAD

**Issue by ThaMacroMan** [minswap/verified-tokens#255]
I messed up my pull request (Badly)! Can this be done by someone who can do it properly? LOL    

 }
   },
  "2cbfa9a4cff67e4ce584dbb9cfe04c7ec9b69d8b3afd39d095f34b4c": {
    "project": "Financial Advice",
    "categories": ["Meme"],
   "socialLinks" {}
   }

**Comment by shadowkora** [comment]
What are your socials? Like Twitter or a website? @ThaMacroMan

**Comment by shadowkora** [comment]
@ThaMacroMan Bump (if there is no reply in 24h I will close this issue)
