### ISSUE TITLE
Verify $HYDRA Token

### ISSUE THREAD

**Issue by HydraCNFT** [minswap/verified-tokens#259]
{
"c8764cd53485b29f6ad94bf69f399ac72903b4df1e70d6a119d6596e": {
"project": "HYDRA",
"categories": ["Launchpad"],
"socialLinks": {
"website": "https://hydraproject.org/",
"twitter": "https://twitter.com/HydraCNFT",
"discord": "https://discord.gg/HydraProject"
}
}
}

**Comment by HydraCNFT** [comment]
{
  "c8764cd53485b29f6ad94bf69f399ac72903b4df1e70d6a119d6596e": {
    "project": "HYDRA",
    "categories": ["Launchpad"],
    "socialLinks": {
      "website": "https://hydraproject.org",
      "twitter": "https://twitter.com/HydraCNFT",
      "discord": "https://discord.gg/HydraProject"
    }
  }
}

**Comment by tvtduy59** [comment]
Hi @HydraCNFT , Please register your token on https://github.com/cardano-foundation/cardano-token-registry . The token logo is a must for the verification process

**Comment by HydraCNFT** [comment]
OK @tvtduy59, our PR has already been approved and we are in the queue waiting for the merge.

**Comment by HydraCNFT** [comment]
Hey @tvtduy59, our PR was merged.
Thank you!

**Comment by HydraCNFT** [comment]
Hey @tvtduy59, our Cardano Foundation PR was merged.
We are ready to be verified. Sorry for the insistence. Thank you!

**Comment by HydraCNFT** [comment]
We've been waiting so long guys... What else can we do to get verified on Minswap? Please just tell us and we'll do it!

@tvtduy59 @mmahut @AndrewWestberg @LHelge
