### ISSUE TITLE
Myth Token

### ISSUE THREAD

**Issue by KosmosKarl** [minswap/verified-tokens#26]
```ts
{
  "987c1f90efe1c95957509b460e0e4f6d6b3f7025a7aca99cd2909037": {
```
    "project": "Adaverse ($MYTH)",
    "categories": ["NFT"],
    "socialLinks": {
      "website": "https://www.adaverse.cc",
      "twitter": "https://twitter.com/AdaverseX",
    }
  }`

**Comment by theuranus** [comment]
Added in the PR: https://github.com/minswap/verified-tokens/pull/64
