### ISSUE TITLE
Please help verify GOAT meme coin

### ISSUE THREAD

**Issue by cirruslycirrus** [minswap/verified-tokens#268]
{
  "6cdafdbee6b403fb5814d8daa26c8aeee9114e3fca2830b480534703": {
    "project": "GOAT",
    "categories": ["Meme"],
    "socialLinks": {
      "twitter": "https://twitter.com/goat_coinada"
    }
  }
}

**Comment by shadowkora** [comment]
Please add your token logo to the [cardano-token-registry](https://github.com/cardano-foundation/cardano-token-registry) so I can verify your PR @cirruslycirrus

**Comment by shadowkora** [comment]
@cirruslycirrus Bump (if there is no reply in 24h I will close this issue)
