### ISSUE TITLE
Verify $Zero Token

### ISSUE THREAD

**Issue by SaedKh** [minswap/verified-tokens#269]
"41a806e6cc38741eb81cc68f6300ee37df0c10b6b99dcb251aa82c3b": {
    "project": "Zero",
    "categories": ["NFT","Meme" ],
    "socialLinks": {
       "website": "https://zero.nmkr.store/",
      "twitter": "https://twitter.com/Zer0Zer0with0"

**Comment by shadowkora** [comment]
Added in #273

**Comment by SaedKh** [comment]
@shadowkora Thank you so much! but is there a reason my website (nft store) doesn't show up ?
