### ISSUE TITLE
help me get veryfied

### ISSUE THREAD

**Issue by Amonkeytoken** [minswap/verified-tokens#279]
{
"policyId": "98986c9f88fbe01cb16af3fb85dcca5c876b5eff68aaa1d5e785b275",
"project": "Astronaut Monkey",
"categories": "Meme" ,
"name": "monkey",
"symbol": "monkey",
"website": "https://astronautmonkeytoken.space/",
"twitter": "",
"discord": "https://discord.gg/KjTFARUMnq",
"description": "Description Astronaut Monkey lets go far away from the moon",
"totalSupply": 1,000,000,000
"amounts": [1],
"decimalPlaces" : 0
}

**Comment by shadowkora** [comment]
Added in #319
