### ISSUE TITLE
Questions regarding Minswap verification

### ISSUE THREAD

**Issue by TJToken** [minswap/verified-tokens#286]
Hello, 

I apologise in advance for the daft questions, but I'm new to this and it's my first time trying something. 

I plan to create a token and have actually have a JSON ready to go. I understand how to create a fork and commit a pull request for cardano verified tokens as there is a youtube video that explains the process, but I am struggling to find any clear information on how to do the rest of it on Minswap verified tokens.

1 - Where exactly do I upload the metadata? For Cardano, you create a fork and click the folder/link labelled "mappings" and add your JSON file there. Which folder do I use on the Minswap verified tokens list?

2 - Exactly what data do I need? From what I've seen, it asks for metadata. Is this the original JSON or something else? If it's something else, where do I find it?

3 - It is my understanding that a liquidity pool must be created first - that is fine, but does the logo need to be added to the coin in the cardano verified tokens section first? If so, how and where do I add the logo?

4 - I also understand I need to add links to social media in the upload, such as Twitter, Discord and a link to the pool on Minswap. How do I format this when processing a pull request?

I'd be greatly appreciative for any help, I know this probably seems elementary to a lot of you, but for me it's been quite the task so far, but I am enjoying the process very much!

Thank you.

**Comment by longngn** [comment]
> Hello,
> 
> I apologise in advance for the daft questions, but I'm new to this and it's my first time trying something.
> 
> I plan to create a token and have actually have a JSON ready to go. I understand how to create a fork and commit a pull request for cardano verified tokens as there is a youtube video that explains the process, but I am struggling to find any clear information on how to do the rest of it on Minswap verified tokens.
> 
> 1 - Where exactly do I upload the metadata? For Cardano, you create a fork and click the folder/link labelled "mappings" and add your JSON file there. Which folder do I use on the Minswap verified tokens list?
> 
> 2 - Exactly what data do I need? From what I've seen, it asks for metadata. Is this the original JSON or something else? If it's something else, where do I find it?
> 
> 3 - It is my understanding that a liquidity pool must be created first - that is fine, but does the logo need to be added to the coin in the cardano verified tokens section first? If so, how and where do I add the logo?
> 
> 4 - I also understand I need to add links to social media in the upload, such as Twitter, Discord and a link to the pool on Minswap. How do I format this when processing a pull request?
> 
> I'd be greatly appreciative for any help, I know this probably seems elementary to a lot of you, but for me it's been quite the task so far, but I am enjoying the process very much!
> 
> Thank you.

Hi thanks for reaching out

1. We contain all tokens' metadata in a single file `tokens.json`
2. Only policy ID, project name and categories are required, the rest are optional
3. Yes, we require a logo added on Cardano Token Registry as well, you can do that when first creating an entry to Cardano Token Registry or update it later.
4. The social media links are optional, the format is in the readme or you can check other tokens in the file

**Comment by GECKadmin1** [comment]
> > Hello,
> > I apologise in advance for the daft questions, but I'm new to this and it's my first time trying something.
> > I plan to create a token and have actually have a JSON ready to go. I understand how to create a fork and commit a pull request for cardano verified tokens as there is a youtube video that explains the process, but I am struggling to find any clear information on how to do the rest of it on Minswap verified tokens.
> > 1 - Where exactly do I upload the metadata? For Cardano, you create a fork and click the folder/link labelled "mappings" and add your JSON file there. Which folder do I use on the Minswap verified tokens list?
> > 2 - Exactly what data do I need? From what I've seen, it asks for metadata. Is this the original JSON or something else? If it's something else, where do I find it?
> > 3 - It is my understanding that a liquidity pool must be created first - that is fine, but does the logo need to be added to the coin in the cardano verified tokens section first? If so, how and where do I add the logo?
> > 4 - I also understand I need to add links to social media in the upload, such as Twitter, Discord and a link to the pool on Minswap. How do I format this when processing a pull request?
> > I'd be greatly appreciative for any help, I know this probably seems elementary to a lot of you, but for me it's been quite the task so far, but I am enjoying the process very much!
> > Thank you.
> 
> Hi thanks for reaching out
> 
> 1. We contain all tokens' metadata in a single file `tokens.json`
> 2. Only policy ID, project name and categories are required, the rest are optional
> 3. Yes, we require a logo added on Cardano Token Registry as well, you can do that when first creating an entry to Cardano Token Registry or update it later.
> 4. The social media links are optional, the format is in the readme or you can check other tokens in the file

Hi, thank you for the reply. Is there a tutorial on adding the logo to the Cardano Token Registry, I can't find how to do it? I understand the rest, I submit the request as per the readme example. If it's incorrect, will someone reply and tell me what is wrong with it? 

Thank you very much

**Comment by GECKadmin1** [comment]
oh also, do I need to create a fork as per the Cardano Token Registry, or do I just add the metadata straight to tokens.json? Thank you

**Comment by GECKadmin1** [comment]
> > Hello,
> > I apologise in advance for the daft questions, but I'm new to this and it's my first time trying something.
> > I plan to create a token and have actually have a JSON ready to go. I understand how to create a fork and commit a pull request for cardano verified tokens as there is a youtube video that explains the process, but I am struggling to find any clear information on how to do the rest of it on Minswap verified tokens.
> > 1 - Where exactly do I upload the metadata? For Cardano, you create a fork and click the folder/link labelled "mappings" and add your JSON file there. Which folder do I use on the Minswap verified tokens list?
> > 2 - Exactly what data do I need? From what I've seen, it asks for metadata. Is this the original JSON or something else? If it's something else, where do I find it?
> > 3 - It is my understanding that a liquidity pool must be created first - that is fine, but does the logo need to be added to the coin in the cardano verified tokens section first? If so, how and where do I add the logo?
> > 4 - I also understand I need to add links to social media in the upload, such as Twitter, Discord and a link to the pool on Minswap. How do I format this when processing a pull request?
> > I'd be greatly appreciative for any help, I know this probably seems elementary to a lot of you, but for me it's been quite the task so far, but I am enjoying the process very much!
> > Thank you.
> 
> Hi thanks for reaching out
> 
> 1. We contain all tokens' metadata in a single file `tokens.json`
> 2. Only policy ID, project name and categories are required, the rest are optional
> 3. Yes, we require a logo added on Cardano Token Registry as well, you can do that when first creating an entry to Cardano Token Registry or update it later.
> 4. The social media links are optional, the format is in the readme or you can check other tokens in the file

Hi, thanks again, I've done some more learning and worked out I need a byte string to get the image to work. I have created the byte string in an image converter, how can I update it on the cardano registry? Thanks

**Comment by longngn** [comment]
> > > Hello,
> > > I apologise in advance for the daft questions, but I'm new to this and it's my first time trying something.
> > > I plan to create a token and have actually have a JSON ready to go. I understand how to create a fork and commit a pull request for cardano verified tokens as there is a youtube video that explains the process, but I am struggling to find any clear information on how to do the rest of it on Minswap verified tokens.
> > > 1 - Where exactly do I upload the metadata? For Cardano, you create a fork and click the folder/link labelled "mappings" and add your JSON file there. Which folder do I use on the Minswap verified tokens list?
> > > 2 - Exactly what data do I need? From what I've seen, it asks for metadata. Is this the original JSON or something else? If it's something else, where do I find it?
> > > 3 - It is my understanding that a liquidity pool must be created first - that is fine, but does the logo need to be added to the coin in the cardano verified tokens section first? If so, how and where do I add the logo?
> > > 4 - I also understand I need to add links to social media in the upload, such as Twitter, Discord and a link to the pool on Minswap. How do I format this when processing a pull request?
> > > I'd be greatly appreciative for any help, I know this probably seems elementary to a lot of you, but for me it's been quite the task so far, but I am enjoying the process very much!
> > > Thank you.
> > 
> > 
> > Hi thanks for reaching out
> > 
> > 1. We contain all tokens' metadata in a single file `tokens.json`
> > 2. Only policy ID, project name and categories are required, the rest are optional
> > 3. Yes, we require a logo added on Cardano Token Registry as well, you can do that when first creating an entry to Cardano Token Registry or update it later.
> > 4. The social media links are optional, the format is in the readme or you can check other tokens in the file
> 
> Hi, thanks again, I've done some more learning and worked out I need a byte string to get the image to work. I have created the byte string in an image converter, how can I update it on the cardano registry? Thanks

you just create a fork of Cardano Token Registry, then push your changes and create a PR to the original repo

**Comment by GECKadmin1** [comment]
Thank you

**Comment by GECKadmin1** [comment]
> > > > Hello,
> > > > I apologise in advance for the daft questions, but I'm new to this and it's my first time trying something.
> > > > I plan to create a token and have actually have a JSON ready to go. I understand how to create a fork and commit a pull request for cardano verified tokens as there is a youtube video that explains the process, but I am struggling to find any clear information on how to do the rest of it on Minswap verified tokens.
> > > > 1 - Where exactly do I upload the metadata? For Cardano, you create a fork and click the folder/link labelled "mappings" and add your JSON file there. Which folder do I use on the Minswap verified tokens list?
> > > > 2 - Exactly what data do I need? From what I've seen, it asks for metadata. Is this the original JSON or something else? If it's something else, where do I find it?
> > > > 3 - It is my understanding that a liquidity pool must be created first - that is fine, but does the logo need to be added to the coin in the cardano verified tokens section first? If so, how and where do I add the logo?
> > > > 4 - I also understand I need to add links to social media in the upload, such as Twitter, Discord and a link to the pool on Minswap. How do I format this when processing a pull request?
> > > > I'd be greatly appreciative for any help, I know this probably seems elementary to a lot of you, but for me it's been quite the task so far, but I am enjoying the process very much!
> > > > Thank you.
> > > 
> > > 
> > > Hi thanks for reaching out
> > > 
> > > 1. We contain all tokens' metadata in a single file `tokens.json`
> > > 2. Only policy ID, project name and categories are required, the rest are optional
> > > 3. Yes, we require a logo added on Cardano Token Registry as well, you can do that when first creating an entry to Cardano Token Registry or update it later.
> > > 4. The social media links are optional, the format is in the readme or you can check other tokens in the file
> > 
> > 
> > Hi, thanks again, I've done some more learning and worked out I need a byte string to get the image to work. I have created the byte string in an image converter, how can I update it on the cardano registry? Thanks
> 
> you just create a fork of Cardano Token Registry, then push your changes and create a PR to the original repo

It's not letting me create a fork as it says the fork has already been created. The token was added to the registry, I'm just trying to add a byte string to the JSON. Just not understanding how to do it :/ thanks for the help
