### ISSUE TITLE
Adding GECK

### ISSUE THREAD

**Issue by GECkAdm1n** [minswap/verified-tokens#292]
{
  "7e4f764cd4283d99b2bbf532d80e8105c3ae58a21b089bce8068170b": {
    "project": “GECK”,
    "categories": [‘Meme”],
    "socialLinks"?: {
      "website"?: https://geckcoinada.com/,
      "twitter"?: https://twitter.com/geckcoinada,
      "discord"?: https://discord.gg/ApPbqBPtgv,  
    }
  }
}

**Comment by GECkAdm1n** [comment]
Could someone please assist in updating this to the verified tokens list? Appreciate it. I can't start a PR as it keeps telling me "there's nothing to compare" after I forked.

**Comment by GECkAdm1n** [comment]
I added a PR with this and in the PR, the text is highlighted red, so I think there's been a mistake made.

If someone could assist, that would be appreciated. 

Thank you

**Comment by GECkAdm1n** [comment]
PR#298 if someone could be kind enough to check it out! I have re done it and I'm not getting any red syntax errors, but I'm not sure if it's right. 

Thank you for any help

**Comment by shadowkora** [comment]
Added in #319
