### ISSUE TITLE
Verify RCCN Token

### ISSUE THREAD

**Issue by gemsnip3r** [minswap/verified-tokens#309]
{
"a3e9d397a62992efd2bb54c954b59044948f11f4e14b28add5ebd847": {
"project": "RCCN",
"categories": ["P2E"],["MemeCoin"],["Utility"]
"socialLinks": {
"website": "https://racoonsclub.io/",
"twitter": "https://twitter.com/racoonscoin",
"discord": "https://discord.gg/racoonsclub"
}
}
}

**Comment by gemsnip3r** [comment]
We send JSON cardano-registry-token before 1 week.

**Comment by shadowkora** [comment]
Seems that the token is still missing its logo @gemsnip3r 
You need to add it in the cardano-token-registry

**Comment by shadowkora** [comment]
Closing this issue due to logo still not being added and a lack of a response, feel free to make this again once the above issue has been resolved
