### ISSUE TITLE
Would like to get a pull request in for token validation of my native utility token $Krypto Coin

### ISSUE THREAD

**Issue by DavidNachman** [minswap/verified-tokens#31]
I am having trouble submitting a pull request for token verification. I have a dev who can do it but I thought I would try myself first. This is for token verification of **$KRYPTO Coin** which is a native utility token for the Krypto Threadz ecosystem

Ticker is: KC
Policy ID: 1111170eb2f1fc2eaf1ea6503c0160eda20de2a84418f988720a7c8e
Twitter: https://twitter.com/KryptoThreadz
Discord: https://discord.gg/2Fs4ERC9Re
Website: https://www.kryptothreadz.com/

Let me know if there is anything else you need from me. Thank you for your time

**Comment by theuranus** [comment]
Hello @DavidNachman , Your token not found on Minswap Dex. No pool was created.

**Comment by DavidNachman** [comment]
Yes there is no liquidity pool set up for my token yet. Just wanted to get verified now so when there is we are already ahead of the game.

**Comment by theuranus** [comment]
Added in https://github.com/minswap/verified-tokens/pull/131
