### ISSUE TITLE
CRDO

### ISSUE THREAD

**Issue by CRDOtoken** [minswap/verified-tokens#318]
{
  "eef4f770d16d2d4c09f0eae47eec8a6c13244d772f45ee41fc822c94": {
    "project": "CRDO",
    "categories": ["Meme"],
	"socialLinks": {
      "website": "https://crdotoken.com/",
      "twitter": "https://twitter.com/CRDOToken",
      "discord": "https://discord.gg/gajcZRbFNU",
      "telegram": "https://t.me/CRDO_Token"      
    }
  }

**Comment by shadowkora** [comment]
Added in #319
