### ISSUE TITLE
Verify $CHE

### ISSUE THREAD

**Issue by checoin2023** [minswap/verified-tokens#339]
{
"$policyId": "f0451f9d13eb8e7c9be861a675d00cc4e0e174f527757b772c4dff18" {
"project": "CheCoin",
"categories": string["Meme"],
"socialLinks"?: {
"twitter"?: "https://twitter.com/checoinada",
"website": "https://checoin.io",
}
}
}

**Comment by checoin2023** [comment]
done

**Comment by checoin2023** [comment]
> Hey @checoin2023, could you please add your policyID to your twitter bio?

done

**Comment by shadowkora** [comment]
Added in #368
