### ISSUE TITLE
$ZOMBIE verification on minswap

### ISSUE THREAD

**Issue by chaucer1973** [minswap/verified-tokens#375]
policy id:  88C7FE7CF68625FD24DC3405432684AE85DA094DCEFF25F81D6664FD

Project:  $ZOMBIE token part of the Maniacal Mannequins ecosystem

Category:   Meme

Launchpad:  Peppermint

https://adamannequins.com/

https://twitter.com/mannequinsnft)

(https://discord.gg/ArtGUbuVHw)

https://www.subber.xyz/maniacal-mannequins-nft)

**Comment by shadowkora** [comment]
Added in #387
