### ISSUE TITLE
Verification for $PAMP

### ISSUE THREAD

**Issue by PampIt58** [minswap/verified-tokens#384]
Hey,
I would like to request assistance in getting my token verified on Minswap.
The pool will be created in the next 29 hours.

The details are as follows:

Name : Pamp
Category :Meme
Policy : 49f81534bdea522df07e40121f6aaf7b2ec0ace1ed5f829f79cf6342
Twitter : https://twitter.com/pampitcoinada?t=zCfHJIcZb0RLj0cNPMLnjw&s=09
Twitter Handle : @pampitcoinada
Discord : https://discord.gg/rvnSqpEv

Thank You

**Comment by shadowkora** [comment]
Hey @PampIt58, your token is missing a logo which is one of our requirements, can you please fix it? (you need to add the logo to the Cardano Token Registry)
Also can you please put the whole policyID (as you have it here) to your Twitter? You only have a partial policyID there

**Comment by PampIt58** [comment]
Hi @shadowkora 
I have gone ahead and fixed the policy id on twitter.
I believe the logo is added.
Let me know if we are good to go, or if you need me to do anything else.
Thank you for the support.
![Capture](https://github.com/minswap/verified-tokens/assets/139324278/edc6f49a-28cd-4d85-a366-33df3157ea4c)

**Comment by shadowkora** [comment]
@PampIt58 The logo has to be added in the Cardano Token Registry as a byte string, if you already made a PR there with the logo then it most likely isn't approved yet
![vvcap 2023-07-13-14-59-13](https://github.com/minswap/verified-tokens/assets/51710571/01f06509-ab58-4fcd-ada8-7e3d6b95d4f9)
