### ISSUE TITLE
$RISK token

### ISSUE THREAD

**Issue by johnnyblessedtran** [minswap/verified-tokens#395]
Hello, I'm from $RISK coin and looks like there are fake verified on Minswap. We want to move LP to MINSWAP
**Discord:** https://discord.gg/riskcoin
**Website**: https://www.riskcoin.io/
**Twitter:** https://twitter.com/RiskCoinAda

**Other DEX:**https://app.vyfi.io/dex?tokenA=lovelace&tokenB=2274b1699f5398170e0497598de7877ebb370ba7b5d25a1d0b2fea075249534b

Policy ID 2274b1699f5398170e0497598de7877ebb370ba7b5d25a1d0b2fea07
(https://github.com/cardano-foundation/cardano-token-registry/pull/3371)

There's a LP already created by someone else, how can we create an LP for $RISK?

**Comment by shadowkora** [comment]
Added in #397
