### ISSUE TITLE
Verification for $ANON

### ISSUE THREAD

**Issue by anonymousada** [minswap/verified-tokens#396]
Hello,
I would like to ask for help to get my token verified on Minswap. The coin already appears in Minswap but has not been added LP yet.

Nome : ANON
Category : Meme, NFT and DAO
Policy : 2e772c16d565203085ffe6f06ae76453c96cebc4b5a965e6248b483c
Twitter : https://twitter.com/anonymous_ada
Discord : [http://discord.gg/VxjSW5YmcQ
Website: https://anonymousada.com/

Other DEX: https://app.vyfi.io/dex?tokenA=lovelace&tokenB=2e772c16d565203085ffe6f06ae76453c96cebc4b5a965e6248b483c414e4f4e

**Comment by JJSchaart** [comment]
Created an pull request, please add your policy ID to the Twitter account.
2e772c16d565203085ffe6f06ae76453c96cebc4b5a965e6248b483c

**Comment by anonymousada** [comment]
Done!

**Comment by shadowkora** [comment]
@anonymousada Please add your token logo to the cardano token registry

**Comment by shadowkora** [comment]
Closing due to a lack of a response
