### ISSUE TITLE
Verification for  $BUKELE token

### ISSUE THREAD

**Issue by falcito25** [minswap/verified-tokens#409]
Hello,
I would like to ask for help to get my token verified on Minswap. The coin has been launched on Minswap.

Name: BUKELE
Category : Defi, NFT, DAO 
Policy : 0c002b51df1a54194819c0990f52d14682bbb3e93a58052e7c81f71c
Twitter : https://twitter.com/BukeleTokensv/
Telegram: https://t.me/+hzARUQpOKgI1MjJh
Discord : https://discord.gg/XgVmTAFw
Website: https://www.bukeletoken.com/

**Comment by shadowkora** [comment]
Added in #421
