### ISSUE TITLE
SuperPeso Verification

### ISSUE THREAD

**Issue by SuperPeso** [minswap/verified-tokens#428]
Good afternoon Minswap team,
Can you please help me to get SuperPeso verified?. 
There is already a LP on Minswap.

Name : SuperPeso
Category : RealFi
Policy : 9b199c2d7d2f8fe66c8da8b843380c2228d3e92aee64a3ee81d9d504
Twitter : https://twitter.com/SuperPesoADA
Reddit : https://reddit.com/R/SuperPeso
Website: https://Superpeso.digital

For your time and help.
Thank you,

**Comment by shadowkora** [comment]
Added in #433
