### ISSUE TITLE
Add New Token FSBN

### ISSUE THREAD

**Issue by TroutsFishbowlian** [minswap/verified-tokens#437]
G'day.

I woulld like to ask for help to get my token verified on Minswap. 

The coin already appears in Minswap, has added LP and is being actively traded.

Name: FSBN
Category: Meme
Policy: 909465f207e30a8f9dfbbcd246a67d6dfb82e4a8d54a2526534bc2cb
JSON: 909465f207e30a8f9dfbbcd246a67d6dfb82e4a8d54a2526534bc2cb4653424e
Twitter: https://twitter.com/FSBN_Token
Discord: https://discord.gg/Kd3nKWm2
Website: https://fishbowlian.io/

**Comment by shadowkora** [comment]
Can you please add a logo for your token in the cardano-token-registry? @TroutsFishbowlian 
It is one of our requirements

**Comment by TroutsFishbowlian** [comment]
I have now added the token / logo to the cardano-token-registry and it has been successfully merged 8 hours ago #3456.
