### ISSUE TITLE
MONKE Coin on the Registry

### ISSUE THREAD

**Issue by JoshTummot** [minswap/verified-tokens#439]
Hi, I have all the information needed to get my coin on the registry. I am not sure if I did it correctly. If someone could check for me or put this file in there that would be appreciated. Thanks.
![a26b5a1b0c8056375f5f87c6dc2f070f MONKE COIN(done)](https://github.com/minswap/verified-tokens/assets/140435010/4cd48366-6211-4f2c-be2e-6e3d686994e5)
[a26b5a1b0c8056375f5f87c6dc2f070fe404ad1320afa2383ec94f814d4f4e4b45-1.txt](https://github.com/minswap/verified-tokens/files/12306068/a26b5a1b0c8056375f5f87c6dc2f070fe404ad1320afa2383ec94f814d4f4e4b45-1.txt)

**Comment by shadowkora** [comment]
Hey @JoshTummot, all this data is for the cardano-token-registry, we have a different format, please check the readme file of this repository.

**Comment by shadowkora** [comment]
Closing due to a lack of a response
