### ISSUE TITLE
RICK Verificatio

### ISSUE THREAD

**Issue by rick-s707** [minswap/verified-tokens#440]
Hi,
I would like to request you to verify the Rick pool on minswap.
Following are all the details.

Policy : 46a10ea00d09fbbbeaeaadd1ccca26d887c34cfe6335fe1c61fb85f4
Project : RICK
Categories : Meme
Twitter : https://twitter.com/Rickcoinada
Discord : discord.gg/wm73hWWnZJ](https://t.co/TlFQZV3Zuk

Thank You

**Comment by shadowkora** [comment]
Added in #448
