### ISSUE TITLE
Add Yeet Coin 

### ISSUE THREAD

**Issue by YeetCoinAda** [minswap/verified-tokens#451]
We just got into the cardano registry. Here is our link tree: https://linktr.ee/yeetcoinada 
The project is considered a meme coin. 
The policy ID is here: 8ee6a10504961bac6531d79bb32a616187252fece59dc0ac90196451
Thanks!

**Comment by YeetCoinAda** [comment]
Please verify whenever you can thanks

**Comment by shadowkora** [comment]
Added in #462
