### ISSUE TITLE
Pls verify UEFA

### ISSUE THREAD

**Issue by billpi1** [minswap/verified-tokens#452]
Hi guys
Please verify UEFA on minswap

Policy id:
4f2a93e7e89d2db75ade14859a0002a8debb25b877145099c32b6ed4

Project name: UEFA fans
Category: Sport
URL: https://uefacoin.info/
Telegram group: https://t.me/uefacoin
Twitter acc: https://twitter.com/uefacoin
Reddit page: https://www.reddit.com/r/uefa_team

Regards

**Comment by shadowkora** [comment]
Verified
