### ISSUE TITLE
Pull request pending

### ISSUE THREAD

**Issue by adateckel** [minswap/verified-tokens#467]
Hi.
Few days ago we created a pull request to add  our token (TECKEL) to your verified-token file.
Could you please check it?

This is the change that we have proposed

},
  "3fc6548aed99326821131fc480ec65a03d01efe92f58978e24ab8e79": {
    "project": "TECKEL $TECKEL",
    "categories": ["DeFi","NFT","DAO"],
    "socialLinks": {
      "twitter": "https://twitter.com/adateckel",
      "discord": "https://discord.gg/2hqxak6vuR",
      "website": "https://teckel.io/"
    }

Thanks in advance!!!!!!

**Comment by shadowkora** [comment]
Verified in #470
