### ISSUE TITLE
$LEXY Coin Verification

### ISSUE THREAD

**Issue by LexyCoinADA** [minswap/verified-tokens#482]
{
  "d244fcb1d038951eb4fcdba0cc77299453ec96d18ac786ccd284cc78": {
    "project": "Lexy",
    "categories": ["Meme"],
    "socialLinks"?: {
      "website"?: string,
      "twitter"?: "https://twitter.com/LexyCoinADA",
      "discord"?: string,
      "telegram"?: string,
      "coinMarketCap"?: string,
      "coinGecko"?: string
    }
  }
}

**Comment by shadowkora** [comment]
@LexyCoinADA Your token is missing its logo in Cardano Token Registry, without it I can't verify your token
