### ISSUE TITLE
Add PROCK udate tokens.json

### ISSUE THREAD

**Issue by TJToken** [minswap/verified-tokens#514]
policyId: bfa9354862e34f2dd417c9068a9367b530d1a704a0f5dc41468c402c
project: PROCK
categories: DeFi
socialLinks
twitter: https://twitter.com/possumrocketada
discord: https://discord.gg/AJpm4mSQ9c
telegram: NA
coinMarketCap: NA
coinGecko: NA

Any help updating this would be greatly appreciated, 

Thank you very much!

**Comment by TJToken** [comment]
{
  "bfa9354862e34f2dd417c9068a9367b530d1a704a0f5dc41468c402c": {
    "project": “PROCK”,
    "categories": ["Meme"],
    "socialLinks"?: {
      "website"?: https://possumrocketada.com/,
      "twitter"?: https://twitter.com/possumrocketada,
      "discord"?: https://discord.com/invite/kKEv5bba6r,  
    }
  }
}

**Comment by TJToken** [comment]
Hi, any update on this please? Added this 2 weeks ago and made a PR not long after. Assistance would be greatly appreciated.

Thank you!

**Comment by shadowkora** [comment]
Already verified
