### ISSUE TITLE
Verify m00n token

### ISSUE THREAD

**Issue by adam00ncoin** [minswap/verified-tokens#526]
{
  "$policyId": { 13383a6b04baefd69c10e05d904f3b05c205a77717e12ee5f5b51b11
    "project": "m00n"
    "categories":  "Meme"
    "socialLinks"?: {
      "website"?: 
      "twitter"?:  https://twitter.com/m00ncoinada
      "discord"?: 
      "telegram"?: 
      "coinMarketCap"?: 
      "coinGecko"?: 
    }
  }
}

**Comment by adam00ncoin** [comment]
{
"13383a6b04baefd69c10e05d904f3b05c205a77717e12ee5f5b51b11": {
"project": “m00n”,
"categories": ["Meme"],
"socialLinks"?: {
"twitter"?: https://twitter.com/m00ncoinada

}
}
}

**Comment by shadowkora** [comment]
Verified in #552
