### ISSUE TITLE
$GRASS verified

### ISSUE THREAD

**Issue by dicaprigoat** [minswap/verified-tokens#530]
"policyId": "32cc9c6c3456bc048d14a4a8e4ee3592e9664e8daac921a8ef52d92a",
"project": "GOAT Tribe",
"categories": "NFT" | "Gaming" | "DAO",
"name": "GRASS",
"symbol": "GRASS",
"website": "https://goattribe.io/",
"twitter": "https://twitter.com/adaGOATS",
"discord": "https://discord.gg/T32WyzmA",
"description": "GRASS Token powers the GOAT Tribe ecosystem",
"totalSupply": 27,182,818,
"amounts": [1],
"decimalPlaces" : 6

**Comment by shadowkora** [comment]
Verified in #552
