### ISSUE TITLE
Please Add $FREYA to tokens.json

### ISSUE THREAD

**Issue by oldracooon** [minswap/verified-tokens#531]
"b2047ac03c18aa07c2ec50f0b9d1cf34db6021f92aa89f2e956602bd": {
    "project": "FREYA",
    "categories": ["Meme"],
    "socialLinks": {
      "website": "https://freyacoin.io/",
      "twitter": "https://twitter.com/freyahoskinson",
      "discord": "https://discord.gg/freyahoskinson"
    }
  }

**Comment by shadowkora** [comment]
No socials are reachable
