### ISSUE TITLE
Please verify this KRAP

### ISSUE THREAD

**Issue by xanthinus** [minswap/verified-tokens#536]
I don't know how to format! Thanks!! See info pasted in below: 

  "$policyId": {3f476f694e08a7c33a3ab2eae470c1fb94e384155197de0bb48db056
    "project": KrapKoin
    "categories": string[], // "Meme" "Memecoin" "Shitcoin"
    "socialLinks"?: {
      "website"?: [string,](https://www.krapkoin.io/)
      "twitter"?: string, https://twitter.com/KrapKoin
      "discord"?: string, https://discord.gg/XQvNXY3Snj

I have the policy id both in Twitter profile and on the footer of the website.  Thanks!!

**Comment by shadowkora** [comment]
Verified in #552
