### ISSUE TITLE
help me verify

### ISSUE THREAD

**Issue by liedobom** [minswap/verified-tokens#538]
{
"$policyId" "000c8f20369902ff7efcf3438d1f93ecdfa5bc77ee69dbc269b0b5a8" : {
      "project": " Help me buy a BMW" ,
    "categories": ["Meme" "Other"] ,
    "socialLinks"?: {
      "website"?: "www.helpmebuyabmw.org",
      "discord"?: "https://discord.gg/WJFgkJYX",
      "telegram": "",
    }
  }
}

**Comment by liedobom** [comment]
my polici is on discord

**Comment by shadowkora** [comment]
I can't verify this token as you're not meeting a few requirements:
- website is invalid
- token is missing a logo
- not meeting minimum TVL requirements
- policyID can't be on Discord

I will close this issue for now, make a new one after you meet all the requirements
