### ISSUE TITLE
$NPM verification

### ISSUE THREAD

**Issue by realbluehead** [minswap/verified-tokens#548]
Can you please add this token? I can not create the PR

"de34e6cfa98de77f9708f1656280edeee79e4f1ce7ab299d9819f112": {
    "project": "Enpimony",
    "categories": ["NFT"],
    "socialLinks": {
      "website": "https://www.enpimony.io",
      "twitter": "https://twitter.com/enpimony",
      "discord": "https://t.co/NqSQaFOxXa?amp=1"
    }
  }

**Comment by shadowkora** [comment]
No policyID on socials

**Comment by realbluehead** [comment]
Added.

**Comment by shadowkora** [comment]
Verified in #584
