### ISSUE TITLE
Verification help

### ISSUE THREAD

**Issue by LondonPass2024** [minswap/verified-tokens#574]
Hi 

Incident created upon the suggestion from your support team. I logged the following two weeks ago which appears wrong: https://github.com/minswap/verified-tokens/pull/556

 Hence, seeking some help for the creation of a properly formed PR for the attached JSON. 

Please let me know if you need anything further. 
[tokens.json](https://github.com/minswap/verified-tokens/files/13905808/tokens.json)

**Comment by shadowkora** [comment]
Verified already
