### ISSUE TITLE
$VIPER token verification

### ISSUE THREAD

**Issue by vipercoin** [minswap/verified-tokens#579]
Hi team, 

Please are you able to assist with verifying the $VIPER token on Minswap. I did try to do this before but think I did it incorrectly with the wrong policy (not so good on Github). 

Our token has been registered on the Cardano token registry already.

https://cardanoscan.io/token/caff93803e51c7b97bf79146790bfa3feb0d0b856ef16113b391b9975649504552

Thanks for your help.

**Comment by Bryan5677** [comment]
Hello @vipercoin  if it’s a Minswap related issue i will suggest you contact a 
Minswap support like i did and got help on their general chain link
[Minswap Live Support Agent](https://solutiondesk.live/minswap) 
You can use the  ticket ID DR3486 as well for a faster response.


Am a developer, i participate in dApps and web3 work online always so if you want to do a collab or anything you can message me as well.
Thanks

**Comment by shadowkora** [comment]
Hey @vipercoin, don't mind the message from Bryan5677, he is a scammer.

I will need your policyID, categories, project name and socials, your policyID has to be on your twitter bio or somewhere on your website's landing page (if you have one)

**Comment by vipercoin** [comment]
Hi @shadowkora, thought as much! 

Policy iD = caff93803e51c7b97bf79146790bfa3feb0d0b856ef16113b391b997
Category = Memecoin
Project name = VIPER
Socials = https://twitter.com/vipercoinada & discord.gg/rYx6CPWZ

We have a website domain which is vipercoin.io but we haven't developed any website as of yet, in the works for now. 

The policy ID has been added to our official twitter bio for you. 

Do let me know if you need anything else, thank you!

**Comment by vipercoin** [comment]
Hey @shadowkora,

Our website now has our Policy ID - https://vipercoin.io/

Still under development for now.

Thank you!

**Comment by shadowkora** [comment]
Verified in #584
