### ISSUE TITLE
$SNAIL token verification

### ISSUE THREAD

**Issue by JuanTelo** [minswap/verified-tokens#580]
Hi team,

Can you assist with the verification of $SNAIL? 

I have attached the json file

[6fbfbd8f90cdc5a89dab46def6edf52dacaf413d332d66c00235fc2d534e41494c.json](https://github.com/minswap/verified-tokens/files/13932644/6fbfbd8f90cdc5a89dab46def6edf52dacaf413d332d66c00235fc2d534e41494c.json)

Thank you in advance for the help

**Comment by shadowkora** [comment]
@JuanTelo This is not our Verification format, this is the format for Cardano Token Registry, nothing to do with us

**Comment by JuanTelo** [comment]
@shadowkora Thank you for the feedback

Please check this one 
[tokens.json](https://github.com/minswap/verified-tokens/files/13943112/tokens.json)

**Comment by JuanTelo** [comment]
@shadowkora any update?

**Comment by shadowkora** [comment]
The token is missing a logo @JuanTelo

**Comment by PinkySnail** [comment]
Good Morning @shadowkora , here is the logo!
![Design sem nome (2)](https://github.com/minswap/verified-tokens/assets/157853313/8ad55b7e-1219-48a0-af0d-532f27de942b)

**Comment by JuanTelo** [comment]
hey @shadowkora, can you check now? I've updated the registry entry. It should have the logo now
