### ISSUE TITLE
BORGZ verifciation

### ISSUE THREAD

**Issue by battleborgznft** [minswap/verified-tokens#581]
},
  "7f376e3d1cf52e6c4350a1a91c8f8d0f0b63baedd443999ebe8fe57a": {
    "project": "BORGZ",
    "categories": ["NFT", "GameFi"],
    "socialLinks": {
      "website": "https://battleborgz.com/",
      "discord": "https://discord.com/invite/Zyyq3nTS2E",
      "twitter": "https://twitter.com/BattleBorgz"
    }

**Comment by battleborgznft** [comment]
I'm opening this issue following our Discord ticket chat, thank you and please let me know if you need any more information.

**Comment by shadowkora** [comment]
@battleborgznft Any reason why the Telegram linked is for Muesliswap?

**Comment by battleborgznft** [comment]
No, sorry, that was a mistake.

**Comment by battleborgznft** [comment]
@shadowkora

**Comment by shadowkora** [comment]
Verified in #601
