### ISSUE TITLE
GARY Verification

### ISSUE THREAD

**Issue by mtusaqua** [minswap/verified-tokens#599]
{
  "$policyId": "8e790936da3037fd18cb3e16eb3f905f6e7dd0d83ae9707690d1d312" {
    "project": "GARY",
    "categories": ["Meme", "DeFi"] 
    "socialLinks": {
      "twitter": "https://twitter.com/memegarygensler",
      "discord": "https://discord.gg/bXuX5hN3"
    }
  }
}

**Comment by mtusaqua** [comment]
Updated

**Comment by shadowkora** [comment]
Verified in #601
