### ISSUE TITLE
$ROOZ Verification

### ISSUE THREAD

**Issue by ROOZcoin** [minswap/verified-tokens#606]
Hi Minswap team! I need help with verifying my token $ROOZ on min swap.

Project: $ROOZ
Category: Meme Coin
Policy ID: 9405f6d1ea2fb47f9af3f8bfdaafa3906dc801382f639fc8f1be3368524f4f5a
Twitter : https://twitter.com/ROOZcoin

**Comment by shadowkora** [comment]
The pool with this policyID doesn't exist, feel free to open a new issue when you fix the policyID
