### ISSUE TITLE
Verify $SLICE token

### ISSUE THREAD

**Issue by crustario** [minswap/verified-tokens#612]
{
  "efb235b213063ca29aa143b934ae624824879a5ae504237e4804191a": {
    "project": "Pizzaverse",
    "categories": ["Meme"],
    "socialLinks": {
      "twitter": "https://twitter.com/pizzaverse_ada",
      "discord": "https://discord.com/invite/m5Qw4bRW7F"
    }
  }
},

**Comment by shadowkora** [comment]
Verified in #635
