### ISSUE TITLE
$SLOW TOKEN VERIFICATION

### ISSUE THREAD

**Issue by SLOWonAda** [minswap/verified-tokens#626]
need some help to verificate our token.

ticker: $SLOW
policy ID: 04e819c9145aa7cc1ef91a8fbc3a31e41fffbb195978e7875ffb93b0
Twitter : @slothoncardano

**Comment by shadowkora** [comment]
Token is missing a logo (needs to be added to Cardano Token Registry

**Comment by SLOWonAda** [comment]
It's done, can you check it?

**Comment by shadowkora** [comment]
Verified in #661
