### ISSUE TITLE
VERIFY $BET

### ISSUE THREAD

**Issue by BullishAlex** [minswap/verified-tokens#633]
{
  "$policyId": {d542ad1dc269ae601125e8259cb8427c6b37c1d3569d10441df0291f
    "project": string, BET
    "categories": string[], “DeFi” “AI” “GameFI”
    "socialLinks"?: {
      "website"?: string, adashuffle.io
      "twitter"?: string, @adashuffle
      "discord"?: string, 
      "telegram"?: string,
      "coinMarketCap"?: string,
      "coinGecko"?: string
    }
  }
}

[IMG_5277](https://github.com/minswap/verified-tokens/assets/160287119/6365516d-3177-4b7f-a7bb-1928e3c102e4)

**Comment by shadowkora** [comment]
Token doesn't meet minimum TVL requirements, feel free to remake the issue when it does
