### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by GMmeme** [minswap/verified-tokens#677]
I would need help with the pull request. thanks!

twitter : https://twitter.com/GMMemeofficial

policy ID: 9f50b54a4bdd46921d3392a3784faf7646e4ee91e3007552f0978568

![4cNawSfe_400x400](https://github.com/minswap/verified-tokens/assets/164567887/6bb6273c-c5d1-49b5-98a4-2a641e7c6fd1)

**Comment by shadowkora** [comment]
Token is missing a logo in the Cardano Token Registry @GMmeme
