### ISSUE TITLE
ANGELS

### ISSUE THREAD

**Issue by CardanoFan777** [minswap/verified-tokens#678]
{
  "$policyId": {285b65ae63d4fad36321384ec61edfd5187b8194fff89b5abe9876da
    "project": string, Angel Finance
    "categories": string[], Defi
    "socialLinks"?: {
      "website"?: string, https://ccardano.gitbook.io/angel-paper
      "twitter"?: string, https://twitter.com/angelcoinada
      "discord"?: string, https://discord.gg/angelfinance
      "telegram"?: string,
      "coinMarketCap"?: string,
      "coinGecko"?: string
    }
  }
}

**Comment by CardanoFan777** [comment]
Hello?

**Comment by shadowkora** [comment]
I can't find your token's policyID anywhere on the socials, please fix that @CardanoFan777

**Comment by CardanoFan777** [comment]
It's in the Links tab of our paper and in our Discord server in it's own channel. It'll also be on the Heaven's Gates staking website when its finished.

https://ccardano.gitbook.io/angel-paper
