### ISSUE TITLE
$BAG Token Verification 

### ISSUE THREAD

**Issue by MMonopoly10** [minswap/verified-tokens#683]
Hello! 

I am having issues submitting my Token Verification. Below is as much as I could fill out 

{
  "$policyId": { 548c390391253aff00af9c95ae310f00803fd28035a6ed6f17c1e5e2
    "project": string,
    "categories": string[], "Meme"
    "socialLinks"?: { https://twitter.com/MMonopoly10
      "website"?: string, https://bagadacoin.com/
      "twitter"?: string, https://twitter.com/MMonopoly10
      "discord"?: string, No Discord
      "telegram"?: string, No Telegram
      "coinMarketCap"?: string, No CoinMarketCap
      "coinGecko"?: string No CoinGecko
    }
  }
}

Thanks!

**Comment by shadowkora** [comment]
Verified in #696
