### ISSUE TITLE
$CARTMAN

### ISSUE THREAD

**Issue by PharaohQuest** [minswap/verified-tokens#687]
Need help setting up new token $CARTMAN to show up on minswap with photo and verification

**Comment by PharaohQuest** [comment]
![IMG_1361](https://github.com/minswap/verified-tokens/assets/165974746/75a05b94-ba2f-447d-817d-014148db9b23)

**Comment by PharaohQuest** [comment]
[c89012d73c965a72363b62a26f1b76b14f2ba9836c0d99398e799cfe434152544d414e.json](https://github.com/minswap/verified-tokens/files/14876479/c89012d73c965a72363b62a26f1b76b14f2ba9836c0d99398e799cfe434152544d414e.json)

**Comment by shadowkora** [comment]
Verified in #696
