### ISSUE TITLE
$BabyPorke Verification on Minswap

### ISSUE THREAD

**Issue by babyporke** [minswap/verified-tokens#688]
{
  "$policyId": {7d9aabc78703947e931e28273a96cf7412039fbd2e54a90ffb17239c
    "project": string,
    "categories": "Meme"
    "socialLinks"?: {https://twitter.com/babyporke
      "website"?: string,
      "twitter"?: [string](https://twitter.com/babyporke),
      "discord"?: [string](https://discord.gg/CHgB9tE6kb),
      "telegram"?: string,
      "coinMarketCap"?: string,
      "coinGecko"?: string
    }
  }
}

**Comment by shadowkora** [comment]
Already verified
