### ISSUE TITLE
Request to Verify BOIS token

### ISSUE THREAD

**Issue by BigBoi4204** [minswap/verified-tokens#693]
"0d35eed3136d050365ef5c3dac5f55e87510d3e27dd79180370ac0f6": {
    "project": "ADA BOIS",
    "categories": ["Meme"],
    "socialLinks": {
      "twitter": "https://twitter.com/BigBoi6547",
      "discord": "https://discord.gg/rQg2xSSvkY"

Hi, my previous pull request had some un resolved issues.
Could you help me with this.

**Comment by shadowkora** [comment]
Already verified
