### ISSUE TITLE
$girls token

### ISSUE THREAD

**Issue by Bella1552** [minswap/verified-tokens#694]
hello i wish to know how to make my girls token verified on minswap. many thanks

**Comment by shadowkora** [comment]
@Bella1552  You will need to provide some info, check the main page of this repository which mentions what you need (or check other issues to see what projects share)

**Comment by Bella1552** [comment]
hi i have the json file. will i need anything else? thanks

**Comment by Bella1552** [comment]
would love to see if i can get it verified today. 
many thanks

**Comment by Bella1552** [comment]
[json girls.txt](https://github.com/minswap/verified-tokens/files/14929799/json.girls.txt)

**Comment by Bella1552** [comment]
$GIRLS 
twitter: @Girlscoinada
discord: discord.gg/GDPGKYmVQD
website: https://girls.iagon.net
meme
policy i.d: [957d1c7fed7152f4cc49e97d5025e4093f72dc7cffd848d5727af495](https://cardanoscan.io/tokenPolicy/957d1c7fed7152f4cc49e97d5025e4093f72dc7cffd848d5727af495)

**Comment by Bella1552** [comment]
https://www.girlsoncardano.com/   new more improved website we have been working on.
