### ISSUE TITLE
Verify $DDOS on minswap

### ISSUE THREAD

**Issue by DegenDino** [minswap/verified-tokens#70]
{
  "2c85a478d53f0e484b852c357e56057dfd8e80a6b72ecb4daffe42e5": {
    "project": "Degen Dino orb Society",
    "categories": ["NFT & DAO"]
    "socialLinks"?: {
      "website"?: "https://barracuda.io/ddos)",
      "twitter"?: "https://twitter.com/DDoS_CNFT",
      "discord"?: "https://discord.com/invite/JvgHRTE8Nv",
    }
  }
}

**Comment by theuranus** [comment]
added in https://github.com/minswap/verified-tokens/pull/78
