### ISSUE TITLE
milfofADA getting verified on minswap

### ISSUE THREAD

**Issue by soffkiller** [minswap/verified-tokens#703]
hi i would like to get milfofADA verified on minswap . thank you 

policy id: "b0c85f93696a9b42ccb833fa5873e0b1655a241459c0a70bf562991b4d696c666f66414441": {
  "project": "milfofADA"
  "categories": ["NFT", "MEME"],
  "twitter": "https://twitter.com/Milfofada"
  "discord": "https://discord.gg/xwetmpmD"

**Comment by shadowkora** [comment]
PolicyID is invalid @soffkiller
