### ISSUE TITLE
$dirt coin verification

### ISSUE THREAD

**Issue by Mutatedmidget** [minswap/verified-tokens#719]
Hello please verify $dirt coin. X account = @dirtcoinada; website = dirtcoin.eu; we have a pool on Minswap with more than 100 $ada tvl.

**Comment by shadowkora** [comment]
Can you please provide your policyID, project name and categories the coin falls under?

**Comment by Mutatedmidget** [comment]
The coin is called Dirt Coin, and it started out as a memecoin, but now is a nature preservance token. You can just say it's a memecoin, that's ok. If there is another choice that fits the bill better then I'm open to suggestions. 

Policy ID that is also on our website: 5f3ef7d0f18403b4f0608f4c860e6f1010872c98606148498c0418a8 (https://dirtcoin.eu/disclaimer)
