### ISSUE TITLE
 VERIFY $BABY

### ISSUE THREAD

**Issue by Asafy77** [minswap/verified-tokens#75]
"389224fd2601bc0d9fcf546430956d8d61b0dc911d6f41d57ccaf7e7": {
"project": "CRYING $BABY TOKEN",
"categories": ["MEME"]
"socialLinks"?: {
"website"?:[ "https://barracuda.io/ddos)",](https://www.cryingbabytoken.com/)
"twitter"?: https://twitter.com/CRING1BABY
THANK YOU

**Comment by theuranus** [comment]
added in https://github.com/minswap/verified-tokens/pull/78
