### ISSUE TITLE
KING TOKEN

### ISSUE THREAD

**Issue by 1zuzutoken** [minswap/verified-tokens#76]
PLEASE VERIFY ON MINSWAP :
$KING TOKEN
TICKER : KING
>

Policy ID | 2edc63d29e94747f7ef65df559260c994d2ecfe208ac6afa56451738
Fingerprint : asset1gz5ssnup9m97ju3z9d522wc3m78krvyed7f8ak
social 👍 
https://twitter.com/KING__cardano
https://www.king4cardano.com
discord : https://discord.com/channels/1060165262508310580/1060165265490456648

**Comment by theuranus** [comment]
added in https://github.com/minswap/verified-tokens/pull/78
