### ISSUE TITLE
babyShitzu

### ISSUE THREAD

**Issue by babyShitzu** [minswap/verified-tokens#813]
{
  "83099a945e95a38d3dc3ab562af81671ed094becf493074251d3f450": {
    "project": "BabyShitzu",
    "categories": ["Meme", "NFT"],
    "socialLinks": {
      "website": "https://babyshitzu.com",
      "twitter": "https://twitter.com/Babyshitzu",
      "discord": "https://discord.gg/fY2Y66kv"
    }
  }
}

**Comment by shadowkora** [comment]
@babyShitzu Your token is missing a logo in the Cardano Token Registry, please fix that as it is one of our requirements

**Comment by babyShitzu** [comment]
just uploaded the token registry with image:

https://github.com/cardano-foundation/cardano-token-registry/commit/66c90bf1e9ca83498b51f721471374b05a454621

**Comment by babyShitzu** [comment]
it took almost 5 days to cardano to upload the file, but finally, the image (logo) was updated on cardano token registry: 

https://cardanoscan.io/token/83099a945e95a38d3dc3ab562af81671ed094becf493074251d3f45062616279536869747a75

 
<img width="431" alt="Captura de pantalla 2024-06-05 a la(s) 9 54 28 a m" src="https://github.com/minswap/verified-tokens/assets/170892394/0bc69830-e90b-4af7-8aca-9ae549fd4af0">
